"""Pydantic schema for the Fireworks ICP demo brief.

This schema defines the structured output produced when SignalForce uses
Fireworks AI to analyze a company against the Fireworks ICP configuration.

The schema is designed for a builder-to-builder GTM workflow demo:
SignalForce uses Fireworks to convert raw GTM signals into structured
account intelligence for AI companies with inference-heavy workloads.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator


class FireworksICPBrief(BaseModel):
    """Structured account intelligence brief for a Fireworks-fit company.

    Generated by asking Fireworks AI to analyze raw company signals against
    the Fireworks ICP configuration and return structured GTM intelligence.
    """

    account_name: str = Field(description="Company or account name")
    fit_score: int = Field(description="0-100 score for Fireworks ICP fit")
    intent_level: Literal["Low", "Medium", "High", "Urgent"]
    matched_signals: list[str] = Field(
        description="Specific signals that make this account relevant"
    )
    why_now: str = Field(
        description="Why this account may have an immediate inference-related need"
    )
    fireworks_relevance: str = Field(description="Why Fireworks is relevant to this account")
    likely_pain_points: list[str] = Field(
        description="Likely inference, model, cost, latency, or scale pains"
    )
    recommended_persona: str = Field(description="Best buyer or technical persona to contact")
    outbound_angle: str = Field(description="The best GTM angle for outreach")
    linkedin_message: str = Field(description="Short casual LinkedIn message under 500 characters")
    cold_email_subject: str
    cold_email_body: str

    # ------------------------------------------------------------------
    # Validators
    # ------------------------------------------------------------------

    @field_validator("fit_score")
    @classmethod
    def fit_score_range(cls, v: int) -> int:
        if not 0 <= v <= 100:
            raise ValueError("fit_score must be between 0 and 100")
        return v

    @field_validator("linkedin_message")
    @classmethod
    def linkedin_message_length(cls, v: str) -> str:
        if len(v) > 500:
            raise ValueError("linkedin_message must be under 500 characters")
        return v

    @field_validator("matched_signals")
    @classmethod
    def matched_signals_not_empty(cls, v: list[str]) -> list[str]:
        if not v:
            raise ValueError("matched_signals must not be empty")
        return v

    @field_validator("likely_pain_points")
    @classmethod
    def likely_pain_points_not_empty(cls, v: list[str]) -> list[str]:
        if not v:
            raise ValueError("likely_pain_points must not be empty")
        return v
